apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: su-ahj94e-go
  janus-idp.io/tekton: su-ahj94e-go
  backstage.io/kubernetes-id: su-ahj94e-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: su-ahj94e-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
