apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: su-ahj94e-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: su-ahj94e-go 
  name: su-ahj94e-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: su-ahj94e-go 
